// The file contents for the current environment will overwrite these during build.
// The build system defaults to the dev environment which uses `environment.ts`, but if you do
// `ng build --env=prod` then `environment.prod.ts` will be used instead.
// The list of which env maps to which file can be found in `.angular-cli.json`.

// `.env.ts` is generated by the `npm run env` command
import env from './.env';

export let environment = {
  name: 'dev',
  production: false,
  version: (((env as any).phee?.version) || ((env as any).npm_package_version) || '0.0.0') + '-dev',
  backend: {
    operations: (window as any)['env']['serverApiUrlOps'] || '/api/v1',
    signatureApiUrl: (window as any)['env']['signatureApiUrl'] || '/api/v1',
    // Route bulk connector calls through the dev proxy to avoid CORS in development
    bulkConnectorOps: (window as any)['env']['bulkConnectorOps'] || '/bulk-connector',
    vouchers: (window as any)['env']['serverApiUrlVou'] || '/api/v1',
    voucherCallbackUrl: (window as any)['env']['callbackUrlVou'] || 'https://webhook.site/',
    account: (window as any)['env']['serverApiUrlAct'] || '/api/v1',
    registeringInstituionId: (window as any)['env']['registeringInstitutionId'] || 'default',
  },
  oauth: {
    // For connecting to Mifos X using OAuth2 Authentication change the value to true
    enabled: (window as any)['env']['oauthEnabled'] || false,
    type: (window as any)['env']['oauthType'] || 'keycloak',
    // Route OAuth server calls through the dev proxy to avoid CORS in development
    serverUrl: (window as any)['env']['oauthServerUrl'] || '/auth',
    realm: (window as any)['env']['oauthRealm'] || 'paymenthub',
    clientId: (window as any)['env']['oauthClientId'] || 'opsapp',
    clientSecret: (window as any)['env']['oauthClientSecret'] || '',
    basicAuth: (window as any)['env']['oauthBasicAuth'] || true,
    basicAuthToken: (window as any)['env']['oauthBasicAuthToken'] || 'Y2xpZW50Og=='
  },
  auth: {
    enabled: (window as any)['env']['authEnabled'] || false,
  },
  tenant: (window as any)['env']['platformTenantId'] || 'fineract_default',
  tenants: (window as any)['env']['platformTenantIds'] || 'fineract_default',
  defaultLanguage: (window as any)['env']['defaultLanguage'] || 'en',
  supportedLanguages: (window as any)['env']['supportedLanguages'] || ['en', 'fr']
};
